Repository AllskyTeam/allsky, pull requests merged in 2021-12, with the labels that each got.

#827 Cleanup: bullseye has problems to detect cameras - workaround
  allsky.sh
Labels: Fixed

#824 cleanup: first exposure with currentRaspistillSetting.shutter_us, so …
  src/mode_RPiHQ_mean.cpp
Labels: Fixed

#819 darkCapture.sh: always output 2-digit temp
  scripts/darkCapture.sh
Labels: bug

#800 Capture.cpp updates and fixes
  src/capture.cpp
Labels: bug, enhancement

#864 Update removeBadImages.sh
  scripts/removeBadImages.sh
Labels: bug

#867 generateForDay.sh: bug in args to timelapse.sh
  scripts/generateForDay.sh
Labels: bug

#868 generateForDay.sh: upload message fix
  scripts/generateForDay.sh
Labels: bug
