Repository AllskyTeam/allsky, pull requests merged in 2021-11, with the labels that each got.

#748 install.sh - avoid error messages
  install.sh
Labels: bug

#742 upload.sh: bug fix with failures
  scripts/upload.sh
Labels: bug

#741 Capture.cpp changes
  src/capture.cpp
Labels: bug, config

#754 endOfNight.sh: source variables.sh first
  scripts/endOfNight.sh
Labels: bug

#762 capture.cpp: getTickCount
  src/capture.cpp
Labels: bug

#731 Check that WebUI is installed
  website/install.sh
Labels: bug

#740 removeBadImage.sh: misc changes/fixes
  scripts/removeBadImages.sh
Labels: bug

#763 darkSubtract.sh: don't force -type TrueColor
  scripts/darkSubtract.sh
Labels: bug

#764 Fixed repeated recompile when no source change
  src/Makefile
Labels: bug

#765 Keogram fixes and other changes
  src/keogram.cpp
Labels: bug, enhancement

#797 Incorrect directory in README.md
  README.md
Labels: bug

#785 gui/install.sh: update sudoers with vcgencmd
  gui/install.sh
  gui/sudoers
Labels: bug, config

#804 postData.sh: use IMAGE_DIR
  scripts/postData.sh
Labels: bug, config

#806 Readme changes
  README.md
Labels: config

#803 Allsky.sh libcamera inop error and exit
  allsky.sh
  variables.sh
Labels: bug, Fixed
