Repository AllskyTeam/allsky, pull requests merged in 2024-12, with the labels that each got.

#4020 Fix error message when the user tries to go to the WebUI but Allsky was not installed
  html/includes/functions.php
Labels: bug, Install / upgrade Issue

#4021 Update viewSettings.php: improve message
  html/allsky/viewSettings.php
Labels: Install / upgrade Issue

#4023 Update checkAllsky.sh: Separate messages when in WebUI
  scripts/checkAllsky.sh
Labels: enhancement, Install / upgrade Issue

#4024 Make "no changes" message easier to see
  html/documentation/css/custom.css
  html/includes/allskySettings.php
Labels: enhancement, Install / upgrade Issue

#4025 Update installUpgradeFunctions.sh: Create file if needed
  scripts/installUpgradeFunctions.sh
Labels: bug, Install / upgrade Issue

#4026 Say when no RPi command was found
  install.sh
  scripts/functions.sh
Labels: bug, Install / upgrade Issue

#4027 Don't run determineCommandToUse() if already run
  install.sh
  scripts/functions.sh
Labels: enhancement, Install / upgrade Issue

#4033 Update 2-bug_report.yml: mention attaching "install.log" if needed
  .github/ISSUE_TEMPLATE/2-bug_report.yml
Labels: enhancement

#4037 Arducam must be with capital A and no other caps
  src/ASI_functions.cpp
Labels: bug, Install / upgrade Issue

#4039 Run postData.sh during installation if needed
  install.sh
  scripts/installUpgradeFunctions.sh
  scripts/makeChanges.sh
Labels: bug, Install / upgrade Issue

#4040 Mention camera must be connected prior to installation
  html/documentation/installations/Allsky.html
Labels: Install / upgrade Issue

#4041 Update removeBadImages.sh: include timelapse in Usage message
  scripts/removeBadImages.sh
Labels: enhancement

#4042 Update Allsky.html: correct typo
  html/documentation/installations/Allsky.html
Labels: bug

#4044 Documentation fixes: fix a few <a> tags
  html/documentation/index.html
  html/documentation/knownIssues.html
Labels: bug

#4046 Check for "Planetary Camera" in ZWO model name
  scripts/functions.sh
Labels: bug, Install / upgrade Issue

#4050 Update generateForDay.sh: remove thumbnail prior to generating timelapse
  scripts/generateForDay.sh
Labels: bug

#4051 Update RemoteServer.html: fix url
  html/documentation/installations/RemoteServer.html
Labels: bug

#4062 Update RemoteServer.html: warning about what page is about
  html/documentation/installations/RemoteServer.html
Labels: enhancement, Install / upgrade Issue

#4064 Update remoteWebsiteInstall.sh: add not about not removing images
  remoteWebsiteInstall.sh
Labels: enhancement

#4065 Update timelapse.sh: check for return code 137
  scripts/timelapse.sh
Labels: bug

#4066 Update remoteWebsiteInstall.sh: Add -p to REMOTE_PORT earlier
  remoteWebsiteInstall.sh
Labels: bug, Install / upgrade Issue

#4067 Update imageSDcard.html: mention /opt/allsky
  html/documentation/explanations/imageSDcard.html
Labels: enhancement

#4075 Update remoteWebsiteInstall.sh: Update version
  remoteWebsiteInstall.sh
Labels: bug

#4081 SC2086 fixes
  .github/workflows/ci_shellcheck.yml
  remoteWebsiteInstall.sh
  scripts/checkAllsky.sh
  scripts/generateForDay.sh
  scripts/installUpgradeFunctions.sh
  scripts/postData.sh
  scripts/postToMap.sh
  scripts/saveImage.sh
  scripts/testUpload.sh
  scripts/utilities/allsky-config.sh
  scripts/utilities/installSamba.sh
Labels: bug

#4089 Update installUpgradeFunctions.sh: fix comparison
  scripts/installUpgradeFunctions.sh
Labels: bug, Install / upgrade Issue

#4096 remoteWebsiteInstall.sh fixes
  remoteWebsiteInstall.sh
Labels: bug

#4099 Fix public.php reload
  html/public.php
Labels: bug

#4113 4111 fix Allsky Website sort order
  html/allsky/allsky.css
  html/allsky/functions.php
  html/allsky/show_thumbnails.php
Labels: bug

#4108 Update overlay.css: change opacity
  html/css/overlay.css
Labels: enhancement

#4115 4114 remove streamDaytime
  html/allsky/controller.js
  scripts/postData.sh
Labels: enhancement

#4123 3823 "allsky.sh --help" doesn't work
  allsky.sh
  html/documentation/changeLog.html
  html/documentation/installations/Allsky.html
  src/allsky_common.cpp
Labels: bug
